[tool]
[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Robin.Wang", email = "3Jg$94sbQ@q1"},
]
dependencies = [
    "langchain>=0.0.154",
]
requires-python = ">=3.10"
license = {text = "MIT"}
